### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by bob-carpenter** [vladimir-ch/odeity#1]
Would you mind adding a license file for your code?  

I understand that Sundials has its own amended BSD license.

There's some info from GitHub here, https://help.github.com/articles/open-source-licensing/, including why not having a license means nobody can use your code!

In the old Google Code repo, https://code.google.com/p/odeity/, the license is shown as MIT, which would work for us.  All I saw in a search of the odeity repo are some code files with a QPL license notice, which won't work for us.

We are thinking of using this for Stan, https://github.com/stan-dev/stan, but for that, we need a non-copyleft license and something compatible with GPLv3 because we need to run from R.

**Comment by vladimir-ch** [comment]
Thanks for pointing this out. All of my source code had MIT license text inserted at the top, but there were a couple of files in `utils/` with QPL license or without a clear license. I removed those and added the BSD 3-clause license text in LICENSE. Do that solve your issue, @bob-carpenter ?

**Comment by bob-carpenter** [comment]
Yes, that's perfect.  Thanks very much.
- Bob
